### ISSUE TITLE
Lnk: Encoding bug in ShellBag0x32

### ISSUE THREAD

**Issue by kkriisgaard** [EricZimmerman/Issues#39]
At the moment, ShellBag0x32 always assumes that the encoding is 1252.

If the magic number is 0x36, it should be Unicode according to [libyal](https://github.com/libyal/libfwsi/blob/master/documentation/Windows%20Shell%20Item%20format.asciidoc#34-file-entry-shell-item), something that my own tests confirm.

**Comment by EricZimmerman** [comment]
do you have a sample lnk file you can share that exhibits the behavior? happy to update it but i want to write a test to make sure it works as expected. you can email it to me at saericzimmerman at gmail

**Comment by EricZimmerman** [comment]
in looking at this closer, it appears i should just treat the 0x32 as I do the x31 and x35 as it does the unicode conversion in those cases. 

confirming this via a test file would be ideal, but i updated the switch statement to have the 32 be treated like a 31 which is how ShellBagsExplorer does it.

**Comment by EricZimmerman** [comment]
last call for this one. as far as i know this is fixed, but i dont have a sample file to test against. my lnk project has been updated with the fix however

happy to test this against a lnk file if you have one with a 0x32 type in it. please let me know

**Comment by kkriisgaard** [comment]
Sorry for not getting back to you sooner. I've been trying (and failing, until now) to replicate the issue, and I wasn't allow to send the original file due to company policy. [This file](https://github.com/EricZimmerman/Issues/files/2460913/testfile-0x36.zip) should be a sufficient test case.

**Comment by EricZimmerman** [comment]
understand on not being able to share. i see 2 lnk files in the jumplist. do both exhibit the issue?

lecmd seems to parse them ok once i extract them. 

running them thru the paces now in all the tools tho

**Comment by EricZimmerman** [comment]
i used jlecmd to dump the lnks out, then parsed them as lnk files. if you can show me where you are seeing the encoding error (and what you expect it to be) that will help too

**Comment by EricZimmerman** [comment]
think i got it.

>>Type: Directory, Value: bågfilee.png

Extension blocks found: 2
---------------------- Block 0 (Beef0004)----------------------
Long name: bågfilee.png
Created: 
Last access: 

---------------------- Block 1 (Beef001a)----------------------
Signature: 0xbeef001a
Size: 26
Version: 0

whereas before it was saying just b

**Comment by EricZimmerman** [comment]
i pushed updates to LECmd, JLECmd, and JumpListExplorer with this fix too.

thanks for the report! please test/verify and if we need to we can reopen

**Comment by kkriisgaard** [comment]
I've run the test on both files, and they provide the correct output now. Thanks for the fix.

I still see two small bugs in the code: You should be checking for 0x36 [here](https://github.com/EricZimmerman/Lnk/blob/master/Lnk/ShellItems/ShellBag0x32.cs#L83), not 0x35. The 0x36 case should also be handled by 0x32 instead, as it represents a file.

**Comment by EricZimmerman** [comment]
Updated the switch and 0x35 --> 0x36. thanks again!
